[server]
# The IP address to bind to, empty will bind to all interfaces
;http_addr =

# The http port to use
;http_port = 3000

# The public facing domain name used to access grafana from a browser
;domain = localhost

# Redirect to correct domain if host header does not match domain
# Prevents DNS rebinding attacks
;enforce_domain = false

[security]
# default admin user, created on startup
admin_user = ${GF_SECURITY_ADMIN_USER}

# default admin password, can be changed before first start of grafana
admin_password = ${GF_SECURITY_ADMIN_PASSWORD}

# used for signing
;secret_key = SW2YcwTIb9zpOOhoPsMm

# disable gravatar profile images
;disable_gravatar = false

# data source proxy whitelist (ip_or_domain:port separated by spaces)
;data_source_proxy_whitelist =

[users]
# disable user signup / registration
allow_sign_up = false

# Allow non admin users to create organizations
;allow_org_create = true

# Set to true to automatically assign new users to the default organization (id 1)
;auto_assign_org = true

# Default role new users will be automatically assigned
;auto_assign_org_role = Viewer

[auth]
# Set to true to disable (hide) the login form, useful if you use OAuth
disable_login_form = false

# How often should auth tokens be rotated (duration). 0s means no rotation
;login_token_rotation = 0s

[auth.anonymous]
# enable anonymous access
enabled = false

# specify organization name that should be used for unauthenticated users
;org_name = Main Org.

# specify role for unauthenticated users
;org_role = Viewer

[auth.basic]
# enable basic auth
enabled = true

[analytics]
# Server reporting, sends usage counters to stats.grafana.org every 24 hours.
reporting_enabled = false

# Google Analytics universal tracking code, only enabled if reporting_enabled is true
;google_analytics_ua_id =

# Google Tag Manager ID, only enabled if reporting_enabled is true
;google_tag_manager_id =

[live]
# Max clients per organization. 0 to disable.
max_connections_per_org = 0

# Enable Grafana Live
enabled = false

# Configuration for specific features
;pipeline_buffer_size = 100
;redis_addr = localhost:6379
;redis_password = ""
;redis_db = 0
;redis_tls = false
;redis_tls_skip_verify = false

[unified_alerting]
# Enable the unified alerting engine, formerly known as "new alerting"
enabled = true

# Remove the legacy [alerting] section as it's deprecated

[feature_toggles]
# enable features
enable = 

[explore]
# Enable the Explore section
enabled = true