apiVersion: 1

datasources:
  - name: Prometheus
    uid: eewyj5dtxw3r4a
    type: prometheus
    access: proxy
    url: ${PROMETHEUS_URL:-http://prometheus:9090}
    isDefault: true
    editable: false
