use_default_settings: true

server:
  secret_key: "CHANGE_ME_TO_A_LONG_RANDOM_SECRET"
  limiter: true
  image_proxy: true

search:
  formats:
    - html
    - json
  safe_search: 0
  default_lang: "he-IL"

engines:
  - name: google
    disabled: false
  - name: bing
    disabled: false
  - name: duckduckgo
    disabled: false
  - name: brave
    disabled: false
  - name: wikipedia
    disabled: false
