{
 "title": "NVIDIA SMI Exporter Dashboard",
 "description": "This dashboard displays metrics from the nvidia-smi exporter.",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "uuid",
    "label": "UUID",
    "query": "label_values(nvidia_smi_temperature_gpu, uuid)"
   }
  ]
 },
 "panels": [
  {
   "title": "GPU Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "nvidia_smi_temperature_gpu{uuid=~\"$uuid\"}",
     "legendFormat": "GPU {{name}}"
    }
   ]
  },
  {
   "title": "GPU Avg. Temp",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "avg(nvidia_smi_temperature_gpu{uuid=~\"$uuid\"})"
    }
   ]
  },
  {
   "title": "GPU Power Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "nvidia_smi_power_draw_watts{uuid=~\"$uuid\"}",
     "legendFormat": "GPU {{name}}"
    }
   ]
  },
  {
   "title": "GPU Power Total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "targets": [
    {
     "expr": "sum(nvidia_smi_power_draw_watts{uuid=~\"$uuid\"})"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "nvidia_smi_utilization_gpu_ratio{uuid=~\"$uuid\"}",
     "legendFormat": "GPU {{name}}"
    }
   ]
  },
  {
   "title": "GPU Framebuffer Mem Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "nvidia_smi_memory_used_mb{uuid=~\"$uuid\"}",
     "legendFormat": "GPU {{name}}"
    }
   ]
  },
  {
   "title": "GPU SM Clocks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "nvidia_smi_sm_clock_mhz{uuid=~\"$uuid\"}",
     "legendFormat": "GPU {{name}}"
    }
   ]
  }
 ]
}